### ISSUE TITLE
Is it possible use Tags by Clozes?

### ISSUE THREAD

**Issue by dcampezano** [Arthaey/anki-tag-tweaks#3]
Hi, do you know any way to use a tag with a especific cloze note?
for ex:
"I have a {{c1::card}} with two clozes and want to put a tag only in the {{c2::second}}"

is it possible?
Thank you for yours add-ons and sorry for my poor English.

**Comment by Arthaey** [comment]
Unfortunately, Anki does not support tags per Card, only per Note. It's [a feature I've asked for](http://anki.tenderapp.com/discussions/ankidesktop/14235-per-card-tagging) before, but there developer of Anki doesn't have plans to do it any time soon.
